name: Integration Tests

on:
  pull_request:

jobs:
  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: user-service integration tests
        run: cd user-service && npm install && npm run integration:test:user && cd ..

      - name: email-service integration tests
        run: cd email-service && npm install && npm run integration:test:email && cd ..

      - name: audit-service integration tests
        run: cd audit-service && npm install && npm run integration:test:audit && cd ..

      - name: Annotations for audit-service
        uses: deblockt/cucumber-report-annotations-action@v1.17
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "audit-service/reports/report.json"
          name: audit-service report
          show-global-summary-report: true

      - name: Annotations for email-service
        uses: deblockt/cucumber-report-annotations-action@v1.17
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "email-service/reports/report.json"
          name: email-service report
          show-global-summary-report: true

      - name: Annotations for user-service
        uses: deblockt/cucumber-report-annotations-action@v1.17
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "user-service/reports/report.json"
          name: user-service report
          show-global-summary-report: true
