name: Build and Push Docker Images

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - id: string
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository }}

      - name: Build the Docker image for user-service
        run: cd user-service && docker build -t ghcr.io/${{ steps.string.outputs.lowercase }}/user-service:latest .

      - name: Push the Docker image of user-service
        run: docker push ghcr.io/${{ steps.string.outputs.lowercase }}/user-service:latest && cd ..

      - name: Build the Docker image for email-service
        run: cd email-service && docker build -t ghcr.io/${{ steps.string.outputs.lowercase }}/email-service:latest .

      - name: Push the Docker image of email-service
        run: docker push ghcr.io/${{ steps.string.outputs.lowercase }}/email-service:latest && cd ..

      - name: Build the Docker image for audit-service
        run: cd audit-service && docker build -t ghcr.io/${{ steps.string.outputs.lowercase }}/audit-service:latest .

      - name: Push the Docker image of audit-service
        run: docker push ghcr.io/${{ steps.string.outputs.lowercase }}/audit-service:latest && cd ..  